service: test-CloudSearchDomain

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, "us-west-2" }
  stage: ${opt:stage, "mxu3" }
  profile: ${opt:profile}
  logRetentionInDays: 14
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudsearch:*
      Resource:
        - "*"

plugins:
  - serverless-webpack
  - serverless-jest-plugin

functions:
  CreateCloudSearchDomain:
    handler: handler.CloudsearchDomainMxu

resources:
  Resources:
    CloudSearchDomain:
      Type: Custom::CloudSearchDomain
      Properties:
        ServiceToken:
          Fn::GetAtt:
            - CreateCloudSearchDomainLambdaFunction
            - Arn
        DomainName: test-cloudsearch-domain-2
          

