service: CloudsearchCloudformationResource

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, "us-west-2" }
  stage: ${opt:stage, "mxu3" }
  profile: ${opt:profile}
  logRetentionInDays: 14
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudsearch:*
      Resource:
        - "*"

plugins:
  - serverless-webpack
  - serverless-jest-plugin

functions:
  CloudsearchDomain:
    handler: handler.CloudsearchDomain

resources:
  Outputs:
    CloudsearchDomainArnRef:
      Description: Exported Ref value for CloudsearchDomain
      Value:
        Fn::GetAtt: [CloudsearchDomainLambdaFunction, Arn]
      Export:
        Name: CloudsearchDomainResourceArn
